.env.dist
- Add CSRF_TRUSTED_ORIGINS env variable example to prevent deployment issues.
It could help to update the official documentation about those mandatory env variables on docker deployments using docker-compose. 
Please correct any missing
=> Update `.env.dist` to fix #151 CSRF missconfigurations

.gitignore, README.md
There is no information about running python manage.py collectstatic in documentation.
Static files should be served via the STATIC_ROOT directory by the webserver, for performance reason and in deploy situation (/app/static/* won't be served directly when debug is set to false)
Moreover, without the collectstatic, using the constant 'settings.STATIC_ROOT' will throw an invalid path exception.
=> [UPDT] Adding 'manage.py collectstatic' in documentation

base/backends.py, base/views.py, employee/not_in_out_dashboard.py, helpdesk/threading.py, horilla_automations/signals.py, leave/threading.py, onboarding/views.py, payroll/threadings/mail.py, payroll/views/component_views.py, recruitment/views.py, recruitment/views/views.py
The way mail_from is handled in the current code is non-compliant and non-working in case of server complying with the protocol. For example, you can't use a MS Exchange server with current code.
The "MAIL FROM:" was using either 'dynamic_username' or 'dynamic_username_with_display_name ' (inconsistent behavior, this pr use only the corrected latter). 
In both case the username field of server mail configuration was used. The username field can be any string : not only a mail address.
In lots of scenario you don't use your email address as smtp username.
In case of Exchange Server, it could be "username@domain" (which can be invalid as an email address lacking the .tld) or "domain/username" which is also not a valid email address...
To fix this we MUST use an email address in MAIL FROM, …
=> [FIX] Complying with RFC5321 regarding MAIL FROM 

base/views.py
The old attribute was used in a recent commit. Replaced by the the correct dynamic_from_email_with_display_name.
=> Wrong mail from attribute

leave/views.py
In the "My Leave request" page, there was a issue where when a leave request was made through one of the cards, it won't send a email. Now when a leave request is made when with one of the cards, an email will be sent.
=> Fixed email not sending when leave request is created from create card

docker-compose.yaml
I encountered authentication errors while setting up PostgreSQL in our Docker environment. Below is the error message that I observed while setting up docker.
``FATAL: password authentication failed for user "postgres" db_1 |``
To resolve this, I updated the `docker-compose.yaml` file to include the following environment variable:
``POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"``
This ensures the database uses SCRAM-SHA-256 for authentication during initialization.
- Resolves authentication errors during database setup.
- Makes the deployment and startup process seamless and reliable.
- Improves security by leveraging SCRAM-SHA-256, a more robust authentication method.
1. Investigated the error message and confirmed the issue was related to the authentication method.
2. Updated the …
=> Add PostgreSQL initdb args for scram-sha-256 authentication

payroll/forms/tax_forms.py
The `python_code` field was previously required, causing form submission failures when left empty. This resulted in an invalid form control error:  
> _"An invalid form control with name='python_code' is not focusable."_  
Additionally, this issue affected modal dialogs using `aria-hidden="true"`, preventing proper focus on form fields.  
Added the following line in the `__init__` method of `FilingStatusForm` to make the field optional:  
```python
self.fields["python_code"].required = False
```  
This allows the form to be submitted without `python_code`, resolving the issue.
=> Make python_code field optional in FilingStatusForm

payroll/methods/payslip_calc.py
Deduction Duplication issue solution #541
When calculating payroll deductions, duplicate entries appear in the results for employees with specific deduction assignments.
I'm not sure if this behavior is intended, but I believe each deduction should be applied only once.
Not tested completely.
=> Deduction Duplication issue solution

asset/views.py
- **Filtered the asset list by `cat_id` in the `asset_list` view** to ensure only assets from the selected category are displayed.  
- **Messages in `asset_information.html` are still not appearing** as expected. Currently investigating the issue.  
- The messages can be displayed by **commenting out the `<span>` inside the `if` block**, but this alters the layout of `asset_information.html`. Looking for a proper fix.
=> filtering asset_list by cat_id in asset_list view

payroll/views/component_views.py
When a new payslip is created, the application redirects to `/payroll/view-payslip/${payslipId}`. However, if the user navigates back, the modal backdrop remains visible because it was not removed on form submission. This happens because the MailThread processing takes an unknown amount of time, preventing immediate redirection.  
Attempting to remove the modal using `onsubmit="$(this).closest('.oh-modal--show').removeClass('oh-modal--show')"` does not fully resolve the issue. Additionally, when navigating back, the browser displays a cached version, preventing the updated list of payslips from appearing.  
**Proposed Solution:**  
Implement the `no_cache` decorator to prevent the browser from serving cached content and ensure that the updated payslip list is always retrieved when …
=> Modal Backdrop Stuck on `/payroll/view-payslip/` After Creating Payslip  and going back using back button.

payroll/templates/payroll/payslip/payslip_table.html
When generating payslips, there are a few recurring issues that need to be addressed:
1. **Hidden Columns Issue**:  
Sometimes, columns in the payslip table get hidden when navigating back after generating a payslip. This issue also occurs when the "Send Mail" button in the payslip table is clicked multiple times (2-3 times). This was because there was typo in the class name when toggling columns in payslip_table.html file
```python
toggleColumns("payslip-column-table","payslipCells") --->  toggleColumns("payslip_column_tab","payslipCells")
```
2. **Backdrop Issue**:  
After generating a payslip and navigating back to the listing page, a backdrop appears unnecessarily. This issue has been partially addressed in PR #563, where the backdrop was removed by using a `no_cache` decorator …
=> Column automatic hiding issue in payslip table

asset/apps.py, horilla_crumbs/context_processors.py
Fix for issue #579
I added the "asset.urls" in APP_URLS
```python
APP_URLS.append("asset.urls")
```
also in context_processor.py file of  horilla_crumbs, i added the :
```python
urlpatterns.append(path("asset/", lambda request: redirect("asset-dashboard")))
```
=> Fixed the breadcrumbs for asset module

.gitignore, base/views.py, horilla_backup/migrations/__init__.py, load_data/payroll_data.json, load_data/payroll_loanaccount_data.json, payroll/signals.py
- PyCharm IDE directory ignored
- Due to ORM query in `init` module, `manage.py migrate` fails because there are no tables created at the very first step.
--  How to reproduce: just try to run manage.py migrate with a fresh empty database.
- Needed to split the payroll app test data to avoid primary key unique constraint. Due to post_save signal in LoanAccount, another instance of Allowance get created when payroll test data is created.
-- How to reproduce: Try to load test data after running manage.py migrate
=> Loading of Test data fails due to unique primary key constraint in Allowance

payroll/signals.py
Fix for #624 
-----
Clicking **"Create"** follows this flow:  
```
'employee-create-personal-info' → (redirection) → 'employee-view-update/<int:obj_id>/'
```  
This results in duplicate contracts because:  
1. In `employee_view_update`, the `employee` object is `None` after redirection.  
2. The `work.save()` method runs again, creating a second contract.  
---
```python
def employee_create_update_personal_info(request, obj_id=None):
"""
Updates employee's personal information.
"""
employee = Employee.objects.filter(id=obj_id).first()
form = EmployeeForm(request.POST, instance=employee)
if form.is_valid():
form.save()  # First contract entry is created here
```
```python
if employee is None:
employee = emp
work = EmployeeWorkInformation.objects.entire().filter(employee_id=employee).first() …
```
=> Fixed the duplicate contract issue

recruitment/views/dashboard.py
🐛 Bug Fix: onboarding_count key error in Recruitment Dashboard
Issue:
The Recruitment dashboard was throwing an error because the onboarding_count key was not properly assigned in the context dictionary, leading to a missing variable in the template.
Fix:
Assigned onboarding_count by counting hired_candidates with start_onboard=True, ensuring the key is always defined and the dashboard renders correctly.
```
"onboarding_count": hired_candidates.filter(start_onboard=True).count()
```
Screenshots:
Before (Error)
After (Working)
=> Fixed Recruitment dashboard throwing error without onboarding_count

base/announcement.py
This PR resolves Issue #632, which caused previously uploaded attachments to be lost when updating an announcement. The fix ensures that if no new attachments are provided during an update, the existing attachments remain unchanged. Previously, whenever an announcement was edited, the attachment field would be cleared unless a new file was uploaded, leading to unintentional data loss.
To address this, the code now retrieves the existing attachments before updating the announcement and ensures they are retained if no new attachments are supplied. 
This improvement enhances user experience by preventing unnecessary file re-uploads and ensuring that attachments persist unless explicitly modified. The fix has been tested by creating announcements with attachments, editing them without …
=>  #632: Fix Issue-Retain Existing Attachments When Updating an Announcement

base/forms.py
@horilla-opensource 
There is a typo in this RotatingWorkTypeAssignForm save method.
In additional data , its using 
```python
rotating_work_type_assign.additional_data["next_shift_index"] = 1 # it should be next_work_type_index
```
and in scheduler.py file of base its searching for this
```python
next_work_type_index = rotating_work_type.additional_data.get(
"next_work_type_index", 0
)
```
This is making the first worktype to be 0th  index only instead it should be one as first already given during creation of rotation.
Also i add ionicons dist folder inside ionicons folder in static, but git is not tracking that. Do you know the reason regarding that. Size of ionicons folder in static is 7mb .
=> Fixed the typo in rotating work type additional data

horilla/horilla_settings.py, payroll/forms/component_forms.py, payroll/models/models.py
Issue #552 fixed
Moved the logic of setting include_active_employees from Deduction Model save method to Deduction Form save method.
Haven't tested completely.
Moved logic here in DeductionForm save method.
```python
def save(self, commit: bool = ...) -> Any:
specific_employees = self.data.getlist("specific_employees")
include_all = self.data.get("include_active_employees")
condition_based = self.data.get("is_condition_based")
if not specific_employees and not include_all and not condition_based:
self.instance.include_active_employees = True
super().save(commit)
.
.
.
```
From DeductionModel save method.
```python
def save(self):
super().save()
```
=> Automatic include_all fixed for Deduction form and Allowance form

docker-compose.yaml
Received this warning when starting application via Docker
```shell
WARN[0000] /[redacted]/horilla/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
Following the warning, I have removed the version attribute.
=> Remove version from Docker Compose file

payroll/methods/payslip_calc.py
Added the `compute_limit` method to both `calculate_based_on_gross_pay` and `calculate_based_on_taxable_gross_pay`. However, the maximum limit switch was selected but not applied when generating the payslip.
=> Max limit was not taken when creating Deduction based on Gross pay and taxable Gross pay.

Dockerfile, docker-compose.yaml
- First equals is added in call with M-Shariq-546
- Version isn't needed any longer in docker-compose
- sh was added in front of ./entrypoint.sh to support windows installation (should be checked on linux)
- Please also note that line endings needed in entrypoint.sh were wrong when checked out, I had to switch to LF here:
That wasn't possible to commit.
=> Fixed installation on Windows 11 Pro using docker CLI

horilla_automations/views/cbvs.py, horilla_automations/views/views.py
The permissions are not allowed for employees which have Horilla Automation permissions allowed via Settings>General Settings>Employee Permissions because of mismatch in app name. This is fix for that.
=> [UPDT] Automation: Fix typo in app name for  permissions_required.

horilla_views/templatetags/generic_template_filters.py
=> (fix) #744 RegEx in double quotes causes SyntaxWarning, should be raw string in single quotes

.dockerignore, docker-compose.yaml
Even though PostgreSQL data already has a backup, it does not include media files (such as image profiles, CV, icon, etc). Such assets are important, so they need to be backed up
=> chore: add docker compose volume for media files
